name = "url_personalize_cloudflare"
type = "rust"

account_id = "a9b62e3846b89730c73258f9753382b5"
workers_dev = true
target_type = "rust"
kv_namespaces = [
    { binding = "user_KV", preview_id = "d98442fdb6224a1181e4b952582c4ff3", id = "f6891fcea2db41bea8d40effb5f5c54b" }
]

[env.production]
route = "miguel-gouveia.me/url*"
zone_id = "b0324acad976fa597a32a1326ce09e18"

